### ISSUE TITLE
am installing a new posty mail_server and it was showing an error ant i post my command line error 

### ISSUE THREAD

**Issue by venkynani** [posty/posty_api#17]
================================================================================
    Error executing action `run` on resource 'execute[bundle exec rake db:migrate]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of bundle exec rake db:migrate ----
    STDOUT: 
    STDERR: /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `map!'
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `materialize'
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs'
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for'
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs'
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs'
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup'
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup'
    	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `<top (required)>'
    	from /root/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from /root/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    ---- End output of bundle exec rake db:migrate ----
    Ran bundle exec rake db:migrate returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cookbooks/posty/recipes/posty.rb
    
    105: execute "bundle exec rake db:migrate" do
    106:   cwd node["posty"]["api"]["location"]
    107:   environment ({'RACK_ENV' => node["posty"]["api"]["rack_env"]})
    108: end
    109: execute "bundle exec rake api_key:generate" do
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cookbooks/posty/recipes/posty.rb:105:in `from_file'
    
    execute("bundle exec rake db:migrate") do
      action "run"
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "bundle exec rake db:migrate"
      backup 5
      cwd "/srv/posty_api"
      environment {"RACK_ENV"=>"production"}
      returns 0
      declared_type :execute
      cookbook_name :posty
      recipe_name "posty"
    end
    
  * service[apache2] action restart
    - restart service service[apache2]

Running handlers:
[2015-03-31T08:12:26-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-03-31T08:12:26-04:00] ERROR: Exception handlers complete
[2015-03-31T08:12:26-04:00] FATAL: Stacktrace dumped to /var/chef-solo/chef-stacktrace.out
Chef Client failed. 5 resources updated in 12.457879386 seconds
[2015-03-31T08:12:26-04:00] ERROR: execute[bundle exec rake db:migrate] (posty::posty line 105) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of bundle exec rake db:migrate ----
STDOUT: 
STDERR: /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `map!'
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `materialize'
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs'
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for'
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup'
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup'
	from /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.9.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /root/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /root/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
---- End output of bundle exec rake db:migrate ----
Ran bundle exec rake db:migrate returned 1
[2015-03-31T08:12:26-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

am tried many typs of sol

**Comment by venkynani** [comment]
@iaddict @chicobico  @lweis  @ben-hx  any one please look at this issue

**Comment by chicobico** [comment]
Is this a vagrant, virtualbox environment or a normal server?
Can you write me more details, how is the command you run before this error occurs?
How is the environment Chef Client -> Chef Server or Chef Solo?

**Comment by aditya-dev** [comment]
@chicobico @lweis @iaddict with new posty setup i am unable to create users

error : 

There was an error saving the user renee: u. n. d. e. f. i. n. e. d. . m. e. t. h. o. d. . `. e. r. r. o. r. !. '. . f. o. r. . #. <. V. i. r. t. u. a. l. U. s. e. r. :. 0. x. 0. 0. 7. f. a. b. 0. d. 4. 5. 0. 2. 0. 8. >.


There was an error saving the user qas: O. p. e. r. a. t. i. o. n. . n. o. t. . p. e. r. m. i. t. t. e. d. . @. . c. h. o. w. n. _. i. n. t. e. r. n. a. l. . -. . /. s. r. v. /. v. m. a. i. l. /. p. m. p. g. e. t. c. e. r. t. c. o. u.

**Comment by chicobico** [comment]
I think its a permission problem the api can not create and chown the folder /srv/vmail/pmpget... to user vmail.
