### ISSUE TITLE
[critical] application breaking after new build 

### ISSUE THREAD

**Issue by aditya-** [posty/posty_api#21]
Hi,
@chicobico @lweis @ben-hx @iaddict 

Today i tried to install posty through vagrant as well as normal installation on both i am getting some errors ..

when i've added new user name its giving following error 
```
There was an error saving the user renee: P. e. r. m. i. s. s. i. o. n. . d. e. n. i. e. d. . -. . /. s. r. v. /. v. m. a. i. l.

```
Response : 

```
{"error":"Permission denied - /srv/vmail"}
```

Requested Headers : 
```
Connection	
close
Content-Length	
42
Content-Type	
application/json
Date	
Wed, 13 May 2015 13:44:05 GMT
Server	
Apache/2.4.7 (Ubuntu)
Status	
500 Internal Server Error
X-Powered-By	
Phusion Passenger 5.0.7


"NetworkError: 500 Internal Server Error - http://prompgetcourse.com/posty_api/api/v1/domains/prompgetcourse.com/users"

```

 i tried creating /srv/vmail but its given me chown issue and i fixed that latter 

its given some wired error ..

its all due to recent build .. the changes in app/models/folder.rb

```
  MAIL_ROOT_FOLDER = "/var/vmail"	to	+  MAIL_ROOT_FOLDER = "/srv/vmail"
```

and some other change affection whole project.

I am requesting you to please look at the issue and fix this

**Comment by chicobico** [comment]
Try using the posty_chef "chef-zero" branch instead of master.
This branch contains the new chef cookbook version for posty and many many improvements.

**Comment by aditya-** [comment]
@chicobico  yes .. but there is no such branch .. can you specify version or branch
