### ISSUE TITLE
Where is the API key?

### ISSUE THREAD

**Issue by DaAwesomeP** [posty/posty_api#22]
I generated the API key and would like to use it with the webUI, but where is the API key?

This is all I get when I generate it:
```
$ rake db:migrate
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-3.2.18/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
```

**Comment by DaAwesomeP** [comment]
I just ofund them in MySQL. This really should be added to the docs.

**Comment by Anjali26** [comment]
Can you tell us how / where did you find the key in mysql?

**Comment by chicobico** [comment]
I just merged a pull request from @prashantjois
