### ISSUE TITLE
Posty support for centos

### ISSUE THREAD

**Issue by stevewker** [posty/posty_api#25]
Previously as of know using posty we can create the servers.  does posty_api supports for mail servers 
creation in centos?????
@iaddict @chicobico can you rply?

**Comment by chicobico** [comment]
You can use posty_api on a centos system.
But the automated installation over chef with posty_chef actually only supports ubuntu.

**Comment by stevewker** [comment]
Along with posty_api does posty_webui also supports for mail servers creation in centos???
@iaddict @chicobico can you rply?

**Comment by chicobico** [comment]
Yes posty_webui and posty_client are also operatingsystem independent
