### ISSUE TITLE
Documentation isn't accessible in modern browser

### ISSUE THREAD

**Issue by alexanderadam** [posty/posty_api#30]
The [mentioned documentation](https://github.com/posty/posty_api#usage) on [posty-soft.org](https://www.posty-soft.org/swaggerv2/posty_api.html) isn't accessible because there is a downgrade of security (https to http).
For example a current version of Chrome will give you the following output:

```
Mixed Content: The page at 'https://www.posty-soft.org/swaggerv2/posty_api.html' was loaded
over HTTPS, but requested an insecure XMLHttpRequest endpoint
'http://posty-api.herokuapp.com/api/v1/swagger_doc.json?auth_token=123456'.
This request has been blocked; the content must be served over HTTPS.
```

**Comment by lweis** [comment]
Hey @alexanderadam,

thanks for the notes it had been fixed!

Did you possibly interest more to develop to party with?
If so write me a mail lweis[at]posty-soft.org
